.PHONY: analysis validate clean

# Prefer a local venv with numpy installed (paper_repro/.venv, see pyproject.toml /
# AUDIT_STAGE2.md for how it was created in the sandbox this repo was built in); fall back to
# the ambient python3 for any environment where `pip install numpy` (or `pip install -e .`) has
# already been run against the system interpreter.
PY := $(shell test -x .venv/bin/python3 && echo .venv/bin/python3 || echo python3)

# Regenerate every category-(a) re-derivable table from paper_repro/data/ into analysis_out/.
# Idempotent: safe to run repeatedly. CPU-only, pure Python stdlib, no GPU/dataset access.
analysis:
	mkdir -p analysis_out/claim1 analysis_out/claim2
	$(PY) scripts/claim1/build_ranking_comparison.py
	$(PY) scripts/claim1/build_pairwise_concordance.py
	$(PY) scripts/claim1/build_force_scaling.py
	$(PY) scripts/claim2/build_dose_response.py
	$(PY) scripts/claim2/build_compensation.py
	$(PY) scripts/claim2/build_same_width_control_B.py
	$(PY) scripts/claim2/build_run_replication_control_C.py
	$(PY) scripts/claim2/build_frontier_ell4_degree_balanced.py
	$(PY) scripts/claim2/build_seed_replication_result.py
	$(PY) scripts/claim2/build_depth_localization.py
	$(PY) scripts/claim2/build_ood_curves_and_contrasts.py
	$(PY) scripts/claim2/build_ood_absolute_effect_robustness.py
	$(PY) scripts/claim2/build_ood_domain_decomposition.py

# Compare every table regenerated by `make analysis` against the corresponding frozen table in
# data/claim1/ or data/claim2/. Exits non-zero on any scientifically meaningful discrepancy.
validate: analysis
	$(PY) scripts/validate.py

clean:
	rm -rf analysis_out/claim1 analysis_out/claim2
