# Adapted for anonymous release from analysis_scripts/repr_probe/stage3b1_extra_owners.py
# source revision withheld for anonymous review, original SHA256 66b15857e1b9939c2de43899a868848d3598b484be5e0b20edc32254ed180cbb
# Logic unchanged; import paths, filesystem paths, and identifying names rewritten.
# Verify with: python3 provenance/check_pipeline.py
"""Checkpoint specifications for the matched-frontier comparison: the frontier points that are
not already among the six checkpoints in lmax_checkpoints.py.

The 5 NEW true-frontier owners this stage adds (from the reconstructed discrete Pareto envelope):
  lmax2 LOWtrue:    sphere=16, step=125000  (C~2.326e16) -- replaces the lmax=2 vs lmax=4 study's dominated LOW pick
  lmax2 MIDtrue:    sphere=32, step=300000  (C~1.079e17) -- replaces the lmax=2 vs lmax=4 study's dominated MID pick
  lmax2 UPPERMID:   sphere=32, step=525000  (C~1.888e17) -- 2026-08-13-audit-era lmax2 ceiling
  lmax4 UPPERMID:   sphere=20, step=200000  (C~9.326e16... corrected C~1.865e17, see below)
  lmax4 NEARMAX:    sphere=24, step=300000  (C~3.347e17) -- true lmax4 frontier owner matched to
                     lmax2's HIGH/near-C_common_max point (w64,s525000, C~3.71e17)

Config snapshots for the 4 new widths (lmax2: 16,32; lmax4: 20,24) were generated by
`the frontier config generator`-equivalent one-off (see
config_snapshots/esen_lmax{2,4}_w{W}_generated.yaml): loaded the lmax=2 vs lmax=4 study's own frozen w40 lmax2
snapshot (lmax2) / the initial pilot's own frozen w10 lmax4 original Hydra config (lmax4), and overrode
only `force_field_module.net.sphere_channels` -- the one field that varies across the width
sweep within a fixed lmax family (verified: `base_net.sphere_channels` stays fixed at 4 in every
snapshot, all other fields identical across widths in this project's config convention).
"""
from __future__ import annotations

import json
from pathlib import Path

from pipeline.kernel.frontier_checkpoints import (
    ARCH_LABEL, WIDTH_LABEL, OwnerSpec,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
LMAX_STUDY_DIR = REPO_ROOT / "analysis_outputs" / "stage3b_lmax2_vs_lmax4_2026_08_16"
LMAX_FRONTIER_DIR = REPO_ROOT / "analysis_outputs" / "stage3b1_true_lmax_frontiers_2026_08_16"
CFG_DIR = LMAX_FRONTIER_DIR / "config_snapshots"
LMAX2_INV = json.loads((LMAX_STUDY_DIR / "stage3b_lmax2_inventory.json").read_text())["records"]
KAPPA_L2 = 217.2151
KAPPA_L4 = 250.9565


def _find_l2(width, step):
    for r in LMAX2_INV:
        if r.get("sphere_channels_from_state_dict") == width and r.get("global_step") == step:
            return r
    raise KeyError(f"lmax2 w={width} s={step} not found in inventory")


def _l2_owner(tag, budget, width, step):
    r = _find_l2(width, step)
    N = r["net_trainable_param_count_from_state_dict"]
    D = r["token_processed"]
    C = KAPPA_L2 * N * D
    return OwnerSpec(
        tag=tag, architecture="esen", architecture_label=ARCH_LABEL["esen"],
        budget_label=budget, width_label=WIDTH_LABEL["esen"], width=width, step=step,
        expected_n=N, D_atom_tokens=D, C_owner=C, C_budget=C, utilization=1.0,
        force_mse_norm=None, ckpt_path=r["checkpoint_path"],
        original_config_path=str(CFG_DIR / f"esen_lmax2_w{width}_generated.yaml"),
        config_name=f"esen_lmax2_w{width}_generated.yaml",
    )


# Exact (N, D, C) pulled from the 2026-08-13 empirical_lmax_adversarial_audit's own
# checkpoint_dataset_evaluated.csv / observed_frontier_owners_all_metrics.csv rows for these
# exact (sphere, step) pairs (both are its own recorded lmax4 force-frontier owner rows).
_LMAX4_EXACT = {
    (20, 200000): dict(N=2144170, D=346575759, C=1.8649009486112646e17,
                        ckpt="<CHECKPOINT_ROOT>/geometric_scaling_checkpoints_esen/esen-sphere-20-neutral-epoch/esen/run_9741258_params_2.1_million/dim_32_step_step=200000.ckpt"),
    (24, 300000): dict(N=2566082, D=519711759, C=3.346812983455683e17,
                        ckpt="<CHECKPOINT_ROOT>/geometric_scaling_checkpoints_esen/esen-sphere-24-neutral-epoch/esen/run_9721434_params_2.6_million/dim_32_step_step=300000.ckpt"),
}


def _l4_owner(tag, budget, width, step):
    exact = _LMAX4_EXACT[(width, step)]
    return OwnerSpec(
        tag=tag, architecture="esen", architecture_label=ARCH_LABEL["esen"],
        budget_label=budget, width_label=WIDTH_LABEL["esen"], width=width, step=step,
        expected_n=exact["N"], D_atom_tokens=exact["D"], C_owner=exact["C"], C_budget=exact["C"],
        utilization=1.0, force_mse_norm=None, ckpt_path=exact["ckpt"],
        original_config_path=str(CFG_DIR / f"esen_lmax4_w{width}_generated.yaml"),
        config_name=f"esen_lmax4_w{width}_generated.yaml",
    )


def build_extra_owners() -> dict[str, OwnerSpec]:
    return {
        "esen_lmax2_LOWtrue_w16_s125000": _l2_owner("esen_lmax2_LOWtrue_w16_s125000", "LOWtrue", 16, 125000),
        "esen_lmax2_MIDtrue_w32_s300000": _l2_owner("esen_lmax2_MIDtrue_w32_s300000", "MIDtrue", 32, 300000),
        "esen_lmax2_UPPERMID_w32_s525000": _l2_owner("esen_lmax2_UPPERMID_w32_s525000", "UPPERMID", 32, 525000),
        "esen_lmax4_UPPERMID_w20_s200000": _l4_owner("esen_lmax4_UPPERMID_w20_s200000", "UPPERMID", 20, 200000),
        "esen_lmax4_NEARMAX_w24_s300000": _l4_owner("esen_lmax4_NEARMAX_w24_s300000", "NEARMAX", 24, 300000),
    }
